### ISSUE TITLE
Design request: Some graphics for Kedro blog posts and other collateral

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-website#104]
Mindful of brand issues, I'd like to discuss a project to create some graphics that can be added to blog posts and newletters, etc, as a visual call to action. I've included a couple on this post as examples, but @Mackay031 and @stephkaiser are likely to have much better ideas, so I've set up a meeting to discuss how to proceed.

<img width="904" alt="Screenshot 2023-04-17 at 14 32 02" src="https://user-images.githubusercontent.com/5180475/232500984-51dd8e14-5ebb-4e95-80a3-749216654829.png">
<img width="898" alt="Screenshot 2023-04-17 at 14 29 23" src="https://user-images.githubusercontent.com/5180475/232500995-4f44d719-531a-4bae-b5b0-40bf6f4a87f1.png">
<img width="896" alt="Screenshot 2023-04-17 at 14 28 25" src="https://user-images.githubusercontent.com/5180475/232501002-3aed13f4-2251-4cfc-91b1-506d474fd98d.png">

![Picture 1](https://user-images.githubusercontent.com/5180475/232769109-249b41c0-6168-4446-92d3-4d67ead74b6c.jpg)

<img width="375" alt="image" src="https://user-images.githubusercontent.com/5180475/234010601-66560e17-251c-4922-9415-5a8d7543bfab.png">

**Comment by stichbury** [comment]
Thinking about this some more, I've realised that what would be even better (and save me keep asking you for help) would be a set of templates that are designed so I can drop in a small amount of text and build my own callout graphics. Let's discuss in our upcoming meeting.

**Comment by Mackay031** [comment]
Sure, we can discuss this. If you have a list of requirements, then we can make a plan.

**Comment by tynandebold** [comment]
This is being covered in this issue: https://github.com/kedro-org/kedro-viz/issues/1333

**Comment by stichbury** [comment]
This is done! Yay!
