### ISSUE TITLE
GIF files aren't displaying on Kedro blog

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-website#109]
This is already a known issue, and I've currently left a b[log post published with a broken GIF in it](url) so that it's possible for easy review and diagnosis/fix testing. 

However, we would like to promote that post a bit more, and it looks rubbish as it is. So I'm creating this ticket to track the issue and discuss it further as needed with @tynandebold and onwards to Netlify if possible.

**Comment by tynandebold** [comment]
Thanks, Jo. Appreciate it.

Latest from Netlify:

> Apr 16, 2023, 7:17 AM EDT
> Hi Tynan,
>  
> This should be rolled out. Next.js Runtime v4.34.0 should include the fix. Can you try to check if that's the version being used for your site now and if the issue is fixed?

I tried it out and told them it still wasn't working for GIFs. 

They replied with the following:

> Apr 22, 2023, 11:53 AM EDT
> Thanks for trying that out. We've re-shared it with the devs.

I'll keep chasing them...

**Comment by stichbury** [comment]
Thanks! I took the GIF down for now because @NeroOkwa was sharing the link and it seemed nicer to have the post without it. Let me know if it needs to go back in for testing/verification. 

Only other thing I can think of is, you know you created a type for YouTube video embedding, is there a similar mechanism for embedding a gif? Otherwise, I suppose I _could_ make a video of each gif and put them on youtube as unlisted, then dump them into the posts that way 🤯

**Comment by tynandebold** [comment]
No similar mechanism for GIFs. They should just work, like static images do, so I don't think there would be a need for a separate content type for them (unless I'm not seeing something?).

**Comment by stichbury** [comment]
I converted the gif to a video and uploaded it as unlisted, then added https://kedro.org/blog/experiment-tracking-with-kedro and that works.

If Netlify don't come back with a solution, we have one now. So you may want to close this ticket and leave them to it, but I'll leave it to you to decided @tynandebold

**Comment by tynandebold** [comment]
I'll keep it open for now. 

Good to see we have a workaround that suits us. Hoping we won't need it forever.

**Comment by tynandebold** [comment]
Update from Netlify:

> Hi Tynan,
>  
> We discussed it further with the devs this week, and these are the latest findings: We might be able to further solve the issue you're seeing, however there's a high chance the images are still going to fail because they will take longer time than the functions can execute for. This is due to the size of the image and the 'sharp' library taking that long to process them. The current alternatives would include:
> 
> 1. Use Contentful's Image CDN directly (you appear to be pulling images from Contentful)
> 2. Use videos instead of GIFs and generate a separate component for videos
> 3. Don't use next/image for GIFs if that's possible based on your setup
> 4. You can try making the source images smaller, but that would lead to loss of quality if you need high-res images

I think we can try number 1 and 3.

**Comment by stichbury** [comment]
I've just re-tested this in case it miraculously fixed itself and it hasn't (see https://kedro.org/api/preview?secret=alskdj19283&slug=explore-kedro-0-19) for an example.

I'm not too bothered because we don't need GIFs right now (I'd rather be able to use the `<script>` approach to embed screen recordings (see #185 above) but it would be a great feature to have at some point, so we can stay trendy and use meme gifs when authors want to do so. Let's keep this open!

**Comment by stichbury** [comment]
They are now working! This is great since it means we can at least upload gifs now for screen capture videos. I'd still prefer to use the script approach because it'll give the user playback controls to pause stuff, but this is a huge step forward for our meme usage!

**Comment by stichbury** [comment]
Think we can close the ticket.

**Comment by astrojuanlu** [comment]
> Think we can close the ticket.

If you say so! 😄 We can reopen otherwise.

**Comment by stichbury** [comment]
Hold on! It's not fixed. It works some of the time but is still unpredictable and inconsistent, so I'm keeping it open. Low priority to resolve but worth bearing in mind as we draft posts.

**Comment by astrojuanlu** [comment]
I saw @stichbury had to turn another GIF into a video for our latest "in the pipeline" newsletter. With your permission @rashidakanchwala @NeroOkwa I'm adding this to the Kedro backlog.

**Comment by astrojuanlu** [comment]
Not sure what changed on Netlify but looks like this isn't happening anymore: https://kedro.org/blog/top-10-features-added-to-the-kedro-ecosystem-in-2024

I'm closing this.
