### ISSUE TITLE
Links in callouts are difficult to see

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-website#117]
See for example https://kedro.org/blog/development-principles-for-opinionated-teams

![image](https://user-images.githubusercontent.com/316517/234697632-1be038c3-ddf0-45f5-8e95-c9436f890cbb.png)

**Comment by tynandebold** [comment]
Yes, agreed.

One for @Mackay031 and @stephkaiser.

**Comment by tynandebold** [comment]
Have a look at #118 for the fixes!
