### ISSUE TITLE
Hero graphic and social media thumbnail for "In the pipeline"

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-website#119]
@astrojuanlu had the great idea of putting out a regular,  monthly "newsletter blog post".

We are going to call it "In the pipeline" with the aim of publishing on the first Wednesday of each month, or close to that. It'll have a mix of Kedro news plus highlight anything we think our audience would be interested in (a roundup of useful articles and/or training).

I'd like to use a specific graphic as a hero image/social media thumbnail each time we post it, so it stands out in the listing as the newsletter. It should still be in the style of the other images, so it doesn't look out of place, but I think having something "special" for that post would help it when we promote regularly online.

@Mackay031 @stephkaiser Perhaps this could be your first experiment with Blender to generate something for use as a graphic?

There's no priority for this -- I am putting the first newsletter post out in w/c 1st May, which is obviously too short notice. So I'll use one of the usual graphics this time, and then switch the graphic in when it's ready and re-use in future posts.

**Comment by tynandebold** [comment]
This relates to #132 as well.

**Comment by stichbury** [comment]
@Mackay031 Please could I have your views on which of the blender images I could use on a regular basis for the "In the pipeline" newsletter blog? https://kedro.org/blog/in-the-pipeline-kedro-news-05-23

**Comment by stichbury** [comment]
@stephkaiser and I have discussed today (26/06) and agreed on a short-list of images. She or @Mackay031 will choose and buy from Getty whichever one they like best, and I'll use it in the upcoming "In the pipeline" and potentially all future posts of that name. It'll need resizing to 1.9:1 for the Hero ("**_Image should be 1200 x 627 pixels (or a 1.91/1 ratio)._**")

**Comment by stephkaiser** [comment]
some options to choose from Getty until we make a custom image for the monthly newsletter 

1. https://www.gettyimages.co.uk/detail/photo/spinning-shape-depicting-the-abstract-concepts-of-royalty-free-image/1417979499?adppopup=true
2. https://www.gettyimages.co.uk/detail/photo/yellow-cloth-cwirls-simulation-background-royalty-free-image/1459586853?adppopup=true
3. https://www.gettyimages.co.uk/detail/photo/wallpaper-abstract-shapes-stock-image-royalty-free-image/1361571526?adppopup=true

**Comment by tynandebold** [comment]
> @stephkaiser and I have discussed today (26/06) and agreed on a short-list of images. She or @Mackay031 will choose and buy from Getty whichever one they like best, and I'll use it in the upcoming "In the pipeline" and potentially all future posts of that name. It'll need resizing to 1.9:1 for the Hero ("**_Image should be 1200 x 627 pixels (or a 1.91/1 ratio)._**")

Just a note on this: "_Image should be 1200 x 627 pixels (or a 1.91/1 ratio)._" That's for the social image, not for the hero. The hero is a square (1x1).
