### ISSUE TITLE
Design/redesign callout boxes for blog

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-website#121]
Discussed in a meeting. We currently have 1 grey callout box which I'm using as a call-to-action box at the end of posts, but also as a callout within posts to highlight information relevant to that topic.

We agreed that we need two boxes.

1. A flexible, relatively generic box to go anywhere in the post, which calls out relevant info. This may commonly contain a graphical asset and a couple of lines of text but the graphic is optional.
2. A box with more obvious Kedro branding, that is typically used as the call to action at the end. Again, this may contain a graphic but that is optional.

Please could I request some designs for these to add to the current callout (or replace it). Many thanks!

**Comment by tynandebold** [comment]
Examples where the callout is used higher up the page:

- https://kedro.org/blog/introducing-your-new-team-lead-kedro

**Comment by astrojuanlu** [comment]
We're not doing this for now.
