### ISSUE TITLE
Slack link has expired on website

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-website#129]
When you've a moment, please could you update the link under the nav, and slack.kedro.org to point to a new invitation link, @tynandebold ?

**Comment by tynandebold** [comment]
What's the link under the nav? I usually only ask the LF to update the share URL.

**Comment by astrojuanlu** [comment]
It's in progress already, we do not control `slack.kedro.org`

**Comment by stichbury** [comment]
OK, fair enough, as long as the link under the slack logo, and the slack.kedro.org link will both be updated, it doesn't matter who does it. Didn't you have an outstanding request out so it didn't expire? Just wondering how this happened.

<img width="739" alt="image" src="https://github.com/kedro-org/kedro-website/assets/5180475/9d904e6e-146c-4208-a6e3-05571a2a461c">
