### ISSUE TITLE
Inline code formatting/design review for the blog

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-website#131]
I would like to ask @Mackay031 to consider whether we could change the blog design. The grey band of highlight when code text is inline is very disruptive when there are a number of code snippets in the text. For example:

<img width="940" alt="image" src="https://github.com/kedro-org/kedro-website/assets/5180475/3492a534-636a-4c5c-835f-fd337abf8c5d">

I think what we probably need is just a small revision to the CSS for inline code (single backtick formatting if you're using GitHub/Slack style editor) -- the font changes but background colour shouldn't be as dark as at present (or stays as it is for normal text) and the outline is curved rather than sharp edged. Example:

> Therefore it needs to be deployed separately as a `tar.gz`  file. It is important to note that the contents inside the `conf` directory needs
> to be zipped and **not** the `conf`  folder entirely. Use the following command to zip the contents inside the conf directory and generate a `conf.tar.gz` file containing all the `catalog.yml`, `parameters.yml` and others for running the Kedro pipeline. It will be used with `spark-submit` for the `--archives` option for unpacking the contents into a `conf` directory.

**Comment by stichbury** [comment]
Here's a great example of a published blog post with the inline code formatting, that shows that it's a bit jarring. I think a small adjustment to CSS would be sufficient to tone down the background colour and smooth the edges, but I'm not a designer, so will leave it for review & proper assessment.

**Comment by stephkaiser** [comment]
I just had a quick look - it currently looks good [on the blog](https://kedro.org/blog/how-to-deploy-kedro-pipelines-on-amazon-emr) however maybe we could go one shade lighter for the grey colour. I also noticed there are two different monospace fonts - is this intentional? or should we align and pick one? 

Need final review from @Mackay031 :)

**Comment by tynandebold** [comment]
Two monospace fonts isn't intentional. Great catch. Are you seeing Roboto Mono and Courier? I think only Courier is the one that's rendering, but I'll double check.

Happy to go one shade lighter with the grey. Let us know which color you end up choosing.

**Comment by stephkaiser** [comment]
yep im seeing both fonts, Roboto Mono as well. One font also looks slightly bigger than the other, i see one is at 90% font size but can't inspect the other font so i'm not sure

**Comment by stephkaiser** [comment]
i'll get back to you on the grey colour 👍

**Comment by Mackay031** [comment]
Thanks for picking up @stephkaiser

**Comment by stephkaiser** [comment]
Apologies for the delay - I am back with the updated grey colour:

Current version has this grey background - **#ecedef**
For the updated version, let's go one shade lighter - **#f2f3f4**

The updated grey colour is one shade lighter following our new colour palette [here](https://www.figma.com/file/2WSNDAdG3JZS7qdaiH6Qz6/Kedro-Component-Library?type=design&node-id=43-4713&mode=design&t=sahoHAitrsp3D7HU-4), and is similar to GitHub's grey colour for code. 

It would be great if we could also match all other code blocks to this new updated grey colour, and match the same monospace font + font colour as well :) see example below, it is a bit difficult to read:
<img width="948" alt="Screenshot 2023-06-23 at 15 22 44" src="https://github.com/kedro-org/kedro-website/assets/31114028/394eea84-e29e-4e8a-bc65-bfeee90800f4">
