### ISSUE TITLE
Design: More hero graphics for upcoming blog posts

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-website#132]
I will shortly run out of graphics to use as hero images for blog posts, as I've burned my way through most of the Getty images we selected for the first set.

Please could I request some more to be purchased and sized as previously. I can put together a list of those I like, but we already had a collection so could just grab some more from that based on what we think works best in the existing posts. I think the white background works better than black personally, and the coloured images are more striking but I'm happy with anything, they're all really nice.

I've separately requested a graphic for one recurring blog post, so it's identifiable, and suggested we use that as a test for Blender creation, but it could just be something we find on Getty, and even just stick with the image i've used so far (https://kedro.org/blog/in-the-pipeline-kedro-news-05-23)

**Comment by tynandebold** [comment]
@stichbury could you please let us know how many images you have left before you run out? We're trying to figure out the timing of with @Mackay031 of the template he's building and don't want to block you.

**Comment by stichbury** [comment]
@tynandebold We have run out...but I'm happy to reuse images on different posts until we can get some new ones.
