### ISSUE TITLE
Syntax highlight for code blocks in the blog

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-website#137]
At the moment, the Contentful editor offers a "code" block, which is fine, but syntax is not colored. It would be a nice addition.

**Comment by stichbury** [comment]
I think it is @astrojuanlu but you have to use lower case `python` in the field where you add the code language.

**Comment by stichbury** [comment]
Take a look at the Python in this post as an example https://kedro.org/blog/how-to-deploy-kedro-pipelines-on-amazon-emr

<img width="312" alt="image" src="https://github.com/kedro-org/kedro-website/assets/5180475/cb4ab54d-1f2f-4fa2-b389-186021f753b6">

**Comment by astrojuanlu** [comment]
Came here to say I was indeed not looking at the right place, thanks!
