### ISSUE TITLE
The two calls to action on top are too similar

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-website#173]
## Description

When I first saw the Kedro website, I was very confused about the two calls to action:

![image](https://github.com/kedro-org/kedro-website/assets/316517/4fd1a08c-926f-419f-b42a-371683ea9a79)

I wanted to "Get started" _and_ I also wanted to take the tutorial... So I remember thinking "whatever, I'll click any of the buttons".

## Possible solutions

One idea could be to rename "Get started" to something that alludes to the installation instructions, like "Install", "Install Kedro", or similar. Still not ideal for me to have 2 calls to action, but marginally better than what we have now?

A more interesting idea would be though to have only one button (can be "get started" or "go to the documentation" or "take the tutorial") and a box right above or below that contains a `pip install kedro` and `conda install -c conda-forge kedro` so that visitors don't even need to click a button to get to the installation instructions. A bit more design work, but potentially more helpful. And also _makes it crystal clear that Kedro is pip-installable, hence Python-based and open-source_.

Ideally all this would be **above the fold**.

**Comment by stichbury** [comment]
Can I propose this (for iteration):

1. We remove the "Tutorial" lozenge but retain "Get started" with the link to the [detailed explanation for setup](https://docs.kedro.org/en/stable/get_started/install.html).
2. We reconsider the "Get started" and "Documentation" links on the top/bottom menus 
<img width="775" alt="image" src="https://github.com/kedro-org/kedro-website/assets/5180475/9197d97f-bf70-46cf-94db-96588017a64d">
as these also tend to redundancy as Get started goes to https://docs.kedro.org/en/stable/get_started/install.html and Documentation goes to the root of the docs. I think the latter is fine, let's retain the Documentation link but instead do the following:

* Can we instead have the "Quick start" menu link go to the bottom "Ready to start" section at the bottom of the page. This section needs some rework as it talks about an "introductory tutorial" but goes to the install section. 

<img width="1338" alt="image" src="https://github.com/kedro-org/kedro-website/assets/5180475/11beab92-4f4a-40cb-b624-5e209afd245d">

Proposed changes to this section:

* I like your suggestion @astrojuanlu of having a really quick start `pip` instruction and also saying in the copy that if you want more, you can view the [docs for setup and install](https://docs.kedro.org/en/stable/get_started/install.html). 

* We can then change that existing "Get started" lozenge from going to https://docs.kedro.org/en/stable/get_started/install.html like we already do at the top, maybe here is where we point to the "Tutorial"

How does that sound?

**Comment by astrojuanlu** [comment]
Sounds perfect!

**Comment by stichbury** [comment]
Awesome, I think the next steps then are for you to provide the copy you think should be in the yellow section, in terms of basic quick start `pip install` and I'll revise if needed into a full set of copy (plus reconsider the top section wording). We can then make a ticket for @tynandebold to implement copy and link changes, plus remove the lozenge, over on the website project. Thanks!

**Comment by stichbury** [comment]
Here's the copy changes for that "yellow" section (in draft until I've confirmed with @astrojuanlu)

**DRAFT**

## Ready to start?

Kedro is an open-source project. Go ahead and install it with pip or conda, or check the [set up documentation](https://docs.kedro.org/en/stable/get_started/install.html) for more details on the prerequisites.

```bash
pip install kedro
``` 

or

```bash
conda install -c conda-forge kedro
```

Then a lozenge, which reads: "Take the tutorial" and links to https://docs.kedro.org/en/stable/tutorial/spaceflights_tutorial.html

**Comment by astrojuanlu** [comment]
The instructions are OK! Maybe I'd reorder it a bit, like

---

Kedro is open-source (Apache 2.0), install it with

```
pip install kedro
```

or

```
conda install -c conda-forge kedro
```

see the [set up documentation](https://docs.kedro.org/en/stable/get_started/install.html) for more details on the prerequisites.

**Comment by stichbury** [comment]
Thanks! I've taken your amends and edited the comment above. @tynandebold that copy is now ready for the changes listed.
