### ISSUE TITLE
Update "Features"

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-website#193]
> I just noticed that the website "Features" page does not seem up-to-date. Section 05 "Coding Standards" mentions that the kedro template uses flake8, isort, and black but seems like the newer version of kedro just uses ruff.

https://linen-slack.kedro.org/t/20216226/hello-all-i-am-new-to-kedro-and-i-was-wondering-what-were-th#3d77e4dc-8dd5-4c90-b15f-2615aee94df4

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-website/pull/194
