### ISSUE TITLE
Final tweaks for the website 

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-website#26]
This is a list of tweaks that designers have asked to do after reviewing the website on my screen. There will be more added to this list once they do a thorough review of the website. 

- the 'Why Kedro' section should be #00000 (black) instead of #0B0B0B 
- for mobile-mode, the margin-top should match the margin-bottom 
- for mobile-mode, 'the Why-Kedro' horizontal tabs cut-off's because of the margin. There should be a gradient indicating there's more tabs to scroll to and select.

**Comment by yetudada** [comment]
Closed in favour of #28
