### ISSUE TITLE
Website enhancements - 6th of April 

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-website#28]
## Description

We're iterating on another version of the website ahead of its release. @GabrielComymQB and @yetudada are also expected to lead Design QA. 

## Assets

- Link to the Figma: https://www.figma.com/file/Qs088xhvBnjqwTFq88S3O7/website_v0?node-id=0%3A1
- Link to the current build: https://kedro-org.github.io/kedro-website/

## Problems
- "It felt like I was scrolling forever on the page."
- "We as engineering missed the contrast so perhaps users would miss it too."
- "The interactive demo breaks the experience on the website." 
- "There are too many features shown on the page." 
- "There is a lot of grey on the website. The command-line interface images are grey too." 

### Design

- [x] Find a way to increase the contrast between the sections, including reducing the amount of grey on the interface
- [x] Reduce the amount of spacing on the website, taking into account the mobile experience as well - can we also look at the spacing in the Features section between the headings like Pipeline Abstraction and the content below?
- [x] Finish the video, at a later stage we can look at something like [the Streamlit video for inspiration](https://streamlit.io/)
- [x] Modify images so that they have consistent sizing and framing

### Engineering

- [x] #29
- [x] #30
- [x] For mobile-mode, the margin-top should match the margin-bottom
- [x] #39

### Design
- [x] We seem to have two different URL link UX experiences, e.g. `View on GitHub` in the Case Studies section vs `Learn More` on the Feature section under the Project Template - can we align on a consistent URL link experience?
- [ ] Increase the size of the CTA buttons, they look quite small when compared to the larger header sizes 
- [ ] See if we can create a greater type hierarchy for header sizing
- [ ] Find an alternative to Carbon so that we can customise the background

### Engineering
- [ ] Make rocket animation on the `Get Started` button
- [ ] Randomise the three features that get shown in the features section
- [x] Find a way to simplify the interactive demo (this change will remove elements on the demo, remove the `Explore Live Demo` and investigate if it's possible to stop the scroll issues when moving across the demo)
- [x] Modify the animation in Testimonials so that it [matches the prototype](https://www.figma.com/proto/3OU7t2Pk3t1pO5eaVi3z0M/Kedro-Prototypes?node-id=421%3A204&scaling=min-zoom&page-id=398%3A70&starting-point-node-id=398%3A182)

**Comment by yetudada** [comment]
After a website review with @Mackay031, I observed the following engineering changes and outstanding design questions/feedback. 

### Engineering
#### Overall changes 

- Contrast between sections has been increased
- Spacing has been reduced on the website

#### Hero Section

- `data science solved` was moved to its own line - to mitigate the weird animation when it switches between `Maintainable` and `Modular` because the word `data` moves around
- Removed the floating ["Introducing Kedro" video](https://www.youtube.com/watch?v=KEdmJ2ADy_M)

### "Why Kedro?"

- The background of the "Why Kedro?" section is lighter
- Made the video placeholder the ["Introducing Kedro" video](https://www.youtube.com/watch?v=KEdmJ2ADy_M)
- Add in an `Explore` button with styling to point towards [What is Kedro?](https://kedro.readthedocs.io/en/stable/introduction/introduction.html) in our documentation 

### Features

- Removed the interactive demo of Kedro-Viz and replaced this with a static image
- Implement the styling on the `Explore Live Demo` button
- Change the last feature to `Project Template`; we realised we mention the pipeline already with the Kedro-Viz feature
- The images for the "Integrations" are ready but not all are SVG
- We might still opt for an experience that allows users to copy code from the website for the code snippets

### Case studies
- Reduced space in this area
- Removed logos from the boxes to reduce consumed space
- Also remove the Sberbank testimonial; we'll have two testimonials initially 

### Testimonials 
- Moved the logo below on the testimonials

### Footer
- Added in the Netlify logo
- Reduced spacing in the footer

### Design

#### Overall changes
- Still need to have consistent UX for external links - will change to text with underline
- Outstanding questions on how to export images (not all of them are SVG)
- Design must think about the colouring of the interfaces that will host the code snippets because they introduce more grey to the site

**Comment by yetudada** [comment]
## Code Snippets

### Project Template

> Uses the `Bash` formatting

```
project-template    # Project folder
├── conf            # Configuration files
├── data            # Local project data
├── docs            # Documentation
├── logs            # Logs of pipeline runs
├── notebooks       # Exploratory Jupyter notebooks 
├── README.md       # README.md explaining your project
├── setup.cfg       # Configuration options for testing and linting
└── src             # Source code for pipelines
```

> _Note:_ This does not show some of the hidden files and folders. Should they be included?

### Data Catalog

> Uses the YAML formatting

```
# Load a Spark DataFrame on S3

weather:
  type: spark.SparkDataSet
  filepath: s3a://your_bucket/data/01_raw/weather*
  credentials: dev_s3
  file_format: csv
```

```
# Save an image created with Matplotlib on Google Cloud Storage

results_plot:
  type: matplotlib.MatplotlibWriter
  filepath: gcs://your_bucket/data/08_results/plots/output_1.jpeg
  fs_args:
    project: my-project
  credentials: my_gcp_credentials
```

We'll need to update the copy for this feature:
```
A series of lightweight data connectors used to save and load data across many different file formats and file systems. Supported file formats include Pandas, Spark, Dask, NetworkX, Pickle, Plotly, Matplotlib and many more. The Data Catalog supports S3, GCP, Azure, sFTP, DBFS and local filesystems. The Data Catalog also includes data and model snapshots for file-based systems.
```

### Pipeline Abstraction

> Uses the `Python` formatting

```
def mean(xs, n):
    return sum(xs) / n


def mean_sos(xs, n):
    return sum(x ** 2 for x in xs) / n


def variance(m, m2):
    return m2 - m * m


variance_pipeline = pipeline(
    [
        node(len, "xs", "n"),
        node(mean, ["xs", "n"], "m", name="mean_node"),
        node(mean_sos, ["xs", "n"], "m2", name="mean_sos"),
        node(variance, ["m", "m2"], "v", name="variance_node"),
    ]
)
```

**Comment by datajoely** [comment]
Only comment is that the variance pipeline catalog names are kind of abstract - I think we need a companion catalog snippet to read in `xs` and persist `v`.
