### ISSUE TITLE
Move to a logo-driven showcase of companies using Kedro

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-website#58]
## Introduction

Request from Debanjan Banerjee: Can we make the clientele tab more on the face like other products like Databricks do?

![image](https://user-images.githubusercontent.com/43755008/186405976-ce23f952-77b4-4fab-aa51-01ea722e735a.png)

I was showing this to a client lead DS and the current roulette style design is a bit difficult to read? The user should be able to read the whole list at once.

**Comment by comym** [comment]
Sure, we actually explored that during the website work. We went the way we went to make things more dynamic and engaging - instead of a flat page. 

Does the same idea come from more people apart from Debanjan Banerjee?

That's easy anyway.

A question I have is:
Do we want to treat the logos as individual pngs with individual hit areas that can link to their websites or do we want to just have a plain all-in-one image?

I do think detaching them from each other and creating the grid ourselves can help on the responsive side of things. 
Having an all-in-one image being scaled down sometimes make things unreadable.

**Comment by tynandebold** [comment]
I also agree with Debanjan. It's too hard to see the companies, and if you want to present and show who's using Kedro it's difficult. I had this experience a couple of weeks ago while giving a demo.

I suggest we build a grid of the logos and each logo has a link area that takes you to how they use Kedro.

**Comment by tynandebold** [comment]
10-minute prototype (without any logos):

![image](https://user-images.githubusercontent.com/16869061/186505257-0ae96f44-56f0-4b47-a197-57925ffc2155.png)

**Comment by DebanjanBanerjeeQB** [comment]
Id actually use the logos , ill tell you why 

- Optics of logos are way higher than names
- If you see other apps , you would find logos and clickables , where clicks would redirect to their website directly
- id also get rid of the boxes and just keep the logos in free form @yetudada  @tynandebold  wdyt ?

**Comment by tynandebold** [comment]
We'll definitely use the logos. The screenshot above was me just hacking away for 10 minutes. Not sure I'd keep them "free form" though. That might not look as clean.

@comym and @Mackay031 will come up with something slick and lovely I'm sure.

**Comment by DebanjanBanerjeeQB** [comment]
Makes sense! Thanks Tylan :)

**Comment by DebanjanBanerjeeQB** [comment]
We usually do a lot of tool demos with clients so if i see a nice template anywhere ill post here for ref

**Comment by DebanjanBanerjeeQB** [comment]
<img width="1199" alt="Screenshot 2022-08-26 at 6 23 07 PM" src="https://user-images.githubusercontent.com/95921104/186958945-9b76a4a1-627f-4387-93cc-890f779e8b1f.png">

**Comment by tynandebold** [comment]
Comment from backlog grooming: development can go ahead and pick the company logos, put them in the grid, link to them, and then sit with design to finesse.

**Comment by Huongg** [comment]
assign this ticket to @Mackay031 so he can work on the logo size and colours to fit into the current website. All the logos are stored in here https://mckinsey.ent.box.com/folder/173294983666?s=r9e9s8c7lnlgyorl3kxkx2xm82ntoygy

**Comment by Mackay031** [comment]
Hi all, just looking at this now. One question: Do we really want to link away with logo clicks. Not sure we want to lose traffic that way? I'll have a look at what others are doing for reference.

**Comment by Huongg** [comment]
hey @Mackay031 with the current implementation on our kedro website, we do open the links in a new tab when users click on the company text anyway, I think it's okay to keep the same behaviour?

**Comment by Mackay031** [comment]
Hi at @Huongg, apologies, yes its fine to link to use cases, providing we have links to use cases for all of these logos

**Comment by DebanjanBanerjeeQB** [comment]
@Mackay031 , @Huongg  , hello! As an end user i dont lose to much , its always a nice to have , tbf if it is a super heavy lift , i would ignore it as the logos of big names are self explanatory enough. Cheers and thanks for your attention to this!

**Comment by Huongg** [comment]
yup we do have links for all these logos @Mackay031 👍 

No worries at all @DebanjanBanerjeeQB thanks for raising this request with us 😄

**Comment by Mackay031** [comment]
So if we add the logos in a grid, this is what it will look like. I had to adjust some of the colours to work on a black background. Ideally we would use monochromatic (white) on a black background but unfortunately not all logos can be one colour (eg NASA),  so we will have to proceed with full colour. What do you think? I feel the various colour hijack the page a little but not so much of a big deal.



![Image](https://user-images.githubusercontent.com/102358798/191272882-908b9e5a-cbfc-4d1d-abd3-9798251a7998.png)

**Comment by DebanjanBanerjeeQB** [comment]
Did designing at one point in my life so i know its easier said than done 😿

**Comment by Mackay031** [comment]
This is what it looks like with all white/monochrome logos. I am not sure if we can mess with brands but this is quite common practice for logo grids. 

![Image](https://user-images.githubusercontent.com/102358798/191292940-5528d034-ba54-44b2-bc0b-e197374cafd6.png)

**Comment by Huongg** [comment]
looks good to me @Mackay031, Do you have the Figma link for it so I can get the measurement for the grid? Or can you let me know the width and height for the grid box, please? And also the gap between them?

**Comment by DebanjanBanerjeeQB** [comment]
Also we have some more big names we would want to add wherein we deployed kedro recently , lemme know who tracks this and we can share some names with them :)

**Comment by Huongg** [comment]
hey @DebanjanBanerjeeQB you can share the companies' names, logos and links to articles or use cases, I can add them in with the new design, or you can make a PR to add them directly in `/components/companies-using-kedro/companies-using-kedro-content.tsx`

**Comment by Mackay031** [comment]
Hey @Huongg, its quite a bespoke grid so I can save out the images at actual size. Unfortunately these types of logo grids always take a lot of playing around with to get right visually.
@DebanjanBanerjeeQB, if there are more logos to add in then I think we should remove some from the current grid. 16 is quite a lot to take in and I think we should cap it at that. Maybe @yetudada can pick the top 16?

**Comment by DebanjanBanerjeeQB** [comment]
Aligned! We should open this question to the whole QB Kedro community , im pretty sure i see some names which i know for a fact are missing and then we work with @yetudada  on what 16 to bring here. 

If that be the direction, would it make sense to change the title from "case studies" to "our partners/our community" or something like "key supporters" , pretty sure you guys/integratives can come up with a much nicer heading , basically i'd want to tell the visitors that there are a lot of companies who use Kedro , but these are the top 16 we want to show , WDYT @Mackay031  @Huongg  ?

**Comment by Mackay031** [comment]
@Huongg I have added the folder 'output' [here](https://mckinsey.box.com/s/mbf8q99jdfaz4ttjrned4qg7bu93w1ot). It is a 4x4 (1232x480px) grid with no padding. Images in the folder have a row and column number and must be added sequentially to fill the grid. Hope this make sense? I have added two references
 images, 'grid' and 'logos in place' to show the whole grid and how it aligns to content in the page.

**Comment by Huongg** [comment]
thank you @Mackay031 

And I agree that we should cap the number to 16 only. Maybe if we already have Telkomsel and Beamery displayed at the top of the Case Study section, we don't have to show their logos in the grid anymore? If we do that we can potentially show 18 use cases, with 2 at the top and 16 logos in the grid.
