### ISSUE TITLE
Research CMS offerings for blog.kedro.org

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-website#61]
## Description

We're starting up our awesome Developer Relations and Technical Writing team and would love to have a home for all of the amazing written content that we will create. This task summarises a design effort to create blog.kedro.org which would allow us to:

 - Push viewership to the Kedro website
 - Be the home for all of the written content by the Kedro team

## Impact areas

We would need to look at how to: 

 - Point users to the blog from the Kedro website
 - The user experience of publishing a new blog
 - What blogging system we would use

**Comment by tynandebold** [comment]
To do:
- Research CMS offerings
  - Requirement: open-source pricing plan (i.e. free)
  - Maybe this: https://strapi.io/pricing-self-hosted
  - Or this: https://www.contentful.com/
  - Or even this? https://ghost.org/
- Research other tech blogs for reference materials and inspiration
- Design an initial concept and layout of a blog landing page (the feed) and a blog's post page

**Comment by stichbury** [comment]
Having recent experience of both ghost and contentful, I'd advocate for ghost over contentful, but both are OK-ish

**Comment by tynandebold** [comment]
From my research, it seems like we'd be fine with the free `Community` plan that [Contentful offers](https://www.contentful.com/pricing/). That would give us:
-  5 users
- Two locales
- 48 content types
- 25,000 records

Ghost doesn't have a free or open-source plan, so we'd have to pay. 

Strapi is free if you self host, though to do that we'd need a lot of architectural overhead via AWS or the like, and we'd have to pay for that, so it wouldn't be free.

Contentful also integrates well with Next.js, which is what the Kedro website is built with, and has a lot of [documentation](https://www.contentful.com/nextjs-starter-guide/) on integrating the two.

**Comment by tynandebold** [comment]
My experience with Contentful has been quick on the uptake time. I think I could get it up and running in one day.

The others I don't know well enough to estimate.

**Comment by tynandebold** [comment]
I'm curious what took a while to customize for you though, even if the usage was basic?

**Comment by stichbury** [comment]
That sounds promising.

So I wasn't directly involved as the other technical content writer in my team took on the burden of working with a (subcontracted) development team to give them requirements. I'm going to ask him now what the main issues he/the team hit upon. It took _months_ 

So [this is the content](https://ably.com/topics) -- this is a [typical article](https://ably.com/topic/the-challenge-of-scaling-websockets), which took me about 15 minutes to upload into the format when I had a draft, so that's not too bad, although I didn't include web snippets.

The alternative (ghost) solution is this blog which is also on the Ably site https://ably.com/blog
I found Ghost easier to use as a CMS than Contentful because it's the basis of Medium and is like any other blog platform (while Contentful is more complex)...but I've no idea either how long it took to set up.

**Comment by tynandebold** [comment]
Interesting. So there are two CMS systems driving different parts of that website? I'm perplexed.

I think it would be nice to use Ghost. It looks promising, it just isn't free.

Do let me know what the issues were for the other technical content writer!

**Comment by tynandebold** [comment]
@stichbury another thought: could we get away with just using Markdown files for posts? Something like [this example](https://raw.githubusercontent.com/vercel/next.js/canary/examples/blog-starter/_posts/hello-world.md)? Any experience with that in the past? If so, how'd you find it?

**Comment by stichbury** [comment]
@tynandebold What does that look like when it's rendered?

I've used Jekyll (nice) and dev.to (not so nice) as markdown blog engines. They're OK but my main issue with them is that the workflow for content put into blogs is better done in a non-markdown solution such as (google docs -- OK, not at QB) or Word. The comment and change tracking workflow is infinitely better IMO.

So I'd be happy with a markdown blog **if** we could find a way to convert word files into markdown fairly smoothly.

Apart from that, my requirements for a blog are something along these lines:

* support for specific authors (each with a byline)
* accessible graphical/video elements
* indexing
* easy post creation 
* post date/update date
* basic styling (including code snippets with language identification, callouts and quotes)
* some level of tagging/categorisation (nice to have)


If we can do that in a markdown solution, I'm happy. WDYT?

**Comment by tynandebold** [comment]
Great points and thoughts, thanks for that.

I think it would be too much engineering to find something that would convert a Word doc into Markdown when our other options give us nearly all your wants from the list above. I like the idea though and will keep it around. There are advantages to it. 

This afternoon I already wired up Contentful and have a sparse and basic page already working: https://deploy-preview-63--kedro-website.netlify.app/posts/what-is-kedro-viz

The only thing on your list that I'm unsure of are code snippets. I'll have to do some digging. There must be a way though.

**Comment by tynandebold** [comment]
@stichbury forgot to show you what that's like when it's rendered. [Here it is](https://next-blog-starter.vercel.app/posts/hello-world).

**Comment by stichbury** [comment]
That's nice! It may be that code snippets are as easy as three backticks in standard text, which creates a markdown block but 🤷

**Comment by tynandebold** [comment]
[Webflow](https://webflow.com/) isn't what we want either, as it's more akin so Squarespace or Wix, e.g. a way to build a website from scratch via drag and drop that's then powered by their CMS.

Contentful is the winner.
