### ISSUE TITLE
Create docs.kedro.org

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-website#64]
## Description

I think we should unite https://kedro.readthedocs.org/ with our Kedro website with something like docs.kedro.org

**Comment by tynandebold** [comment]
Let's check in the readthedocs documentation if they can handle a custom domain, a la GitHub pages.

**Comment by tynandebold** [comment]
@yetudada since the LF is so quick to setup subdomains for us, should we simply have them create a `docs.kedro.org` subdomain that points to https://kedro.readthedocs.org/?

**Comment by stichbury** [comment]
> @yetudada since the LF is so quick to setup subdomains for us, should we simply have them create a `docs.kedro.org` subdomain that points to https://kedro.readthedocs.org/?

I think we should.

[readthedocs does support custom domains](https://docs.readthedocs.io/en/stable/custom-domains.html)

**Comment by stichbury** [comment]
@tynandebold If we add redirects (from RTD -> docs.kedro.org) -- what happens to the existing redirects that we've set up on RTD?

For example:

1. I moved a page this release and have set a redirect inside RTD to take care of kedro.readthedocs.io/oldpage -> kedro.readthedocs.io/newpage
2. We later change the subdomain and publish page at docs.kedro.org/newpage
3. What do we do with the redirect inside RTD? Do we need to do anything? If someone clicks a blog link for kedro.readthedocs.io/oldpage what is going to happen?

**Comment by tynandebold** [comment]
I don't know the answer to this, I'll need to look into it.

A question I have first is which way do we want to redirect to go? The two options:

1. RTD -> docs.kedro.org
2. docs.kedro.org -> RTD

I was thinking we'd do the second, though maybe I'm wrong.

**Comment by tynandebold** [comment]
After taking with Jo, the answer is neither point one or two. Rather, we want to add a [custom domain](https://docs.readthedocs.io/en/stable/custom-domains.html) to our readthedocs instance. Therefore anytime someone views the docs, the page's domain will be **docs.kedro.org/asfd**.

**Comment by astrojuanlu** [comment]
Asked our question about Read the Docs redirects https://github.com/readthedocs/readthedocs.org/issues/9988

**Comment by astrojuanlu** [comment]
RTD staff confirmed that

1. First the custom domain redirect takes place: `project.readthedocs.io/path/ -> custom domain/path/`
2. Second the other redirects take place: `/path/ -> /new-path/`

[here's an example with an existing project](https://github.com/readthedocs/readthedocs.org/issues/9988#issuecomment-1427687513).

**Comment by tynandebold** [comment]
Great, thank you for getting to the bottom of that.

Now let's be explicit about what we want the URL to look like. Is it:

- **docs.kedro.org** (a subdomain)?
- **kedro.org/docs** (a subfolder)? I don't think this is technically feasible, so it probably has to be the former.

What do you think?

cc @stichbury

**Comment by stichbury** [comment]
I think we should just go with docs.kedro.org. There doesn't seem to be explicit support for a subfolder according to the docs: 

https://docs.readthedocs.io/en/stable/custom-domains.html

There is some evidence/discussion that subfolders are better (here's an old example, https://moz.com/blog/subdomains-vs-subfolders-rel-canonical-vs-301-how-to-structure-links-optimally-for-seo-whiteboard-friday but I did some checking around and the debate still seems to be raging). However, we live with what we have, and I don't see it as hugely significant.

@tynandebold Shall we give this a try sometime in the next sprint after you return from leave?

**Comment by tynandebold** [comment]
Sounds good. Yes definitely, we'll try it out in the next sprint.

**Comment by tynandebold** [comment]
This is completed.
