### ISSUE TITLE
Upgrade Next.js to v13 and ReactJS to 18.2

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-website#68]
Next.js release a new [major version](https://nextjs.org/blog/next-13).  Also latest Next.js has dependency on latest ReactJS@18.2.0.

We should upgrade to latest Next.js & ReactJS.

Note there are breaking changes in Next.js, most notably in the `<Image />` component.

**Comment by jitu5** [comment]
@tynandebold To upgrade Next.js to v13. It have minimum requirement for ReactJS@18.2.0 but Kedro website is on v17.0.2.
Do we still need to go ahead with this? If yes Do we need a separate ticket for ReactJS v18 upgrade  ?

**Comment by tynandebold** [comment]
Can you upgrade both in one go and augment this ticket to reflect that change?
