### ISSUE TITLE
Logo board: update logos to add other known logos to Community section

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-website#75]
I am compiling a list of additional companies/organisations that use Kedro so we can extend our logos board. 

So far: WovenLight (but I'm going to try to track down whether Elsevier and Expedia can go up there too). Any others @yetudada ?

We could also do with some additional Testimonials, so I'll see what copy I can come up with ASAP to update that section.

**Comment by tynandebold** [comment]
Sounds great.

We should ping some new joiners to our Slack channel that state what companies they work at and see if they'd be willing to provide a testimonial.

**Comment by tynandebold** [comment]
I'm going to close this since we updated the logos section during the rebrand and adding in new companies didn't seem like a priority. We can reopen if we want to add more.
