### ISSUE TITLE
Create and style the blog article page based on finished designs

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-website#80]
## Description

Do all the necessary layout and styling work for the blog article page. The latest design is [here](https://www.figma.com/file/e2FveRnPmCidpGnuyTWbGj/Kedro-Blog-Ideas?node-id=8%3A51336&t=gy7XoVAR83uTeR6L-1).

### Acceptance criteria

- [x] Hero
- [x] Body text and headers
- [x] Sticky side navigation
- [x] Code highlighting (inline and block)
- [x] Blockquote
- [x] Media (image/video)
- [x] Conclusion
- [x] Author details
- [ ] Related posts (maybe?)

**Comment by astrojuanlu** [comment]
_Coming from https://github.com/kedro-org/kedro-website/issues/81#issuecomment-1413467023_

I believe the blog should have an Atom or RSS feed. Perhaps it's not necessary to block #81 on it, but probably would be good to have before publishing the first post there. May we continue the discussion here, or should I open a new issue for it?

**Comment by tynandebold** [comment]
Opening a new issue would be best, since this one will close when I merge #81. Thank you!

**Comment by astrojuanlu** [comment]
Done #82 thanks @tynandebold!

**Comment by tynandebold** [comment]
Closed via #81.
