### ISSUE TITLE
Add Atom or RSS feed to the blog

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-website#82]
Atom and RSS are still popular ways to consume web content nowadays: as one data point, the Feedly news reader accumulates 5M+ downloads today (even years after the demise of Google Reader, which still many people mourn). RSS (generic term for syndication, often including RSS 2.0 and Atom 1.0) provides nice machine-to-machine automation capabilities as well - for example, subscribing a Slack channel to an RSS feed, or generating a Mailchimp newsletter from such feed. And finally, it's a nice touch showing that we care about the open web, which is making a comeback now.

I'm on the fence on whether we should offer the full content in the feed, or just an excerpt or summary with a link to the full blog post. If the purpose of the blog is to draw attention to Kedro itself, we might want to draw visitors to the blog, and hence serve partial feeds.

Thoughts?

(Context: https://github.com/kedro-org/kedro-website/issues/80 and #81)

**Comment by tynandebold** [comment]
I'm for the idea as a whole. I don't have a strong preference for full content or partial. I see pros and cons. I like your point of wanting to draw visitors to the blog, so for that reason alone I think we should serve a partial feed and link to the full post.

**Comment by tynandebold** [comment]
Done via #87.
