### ISSUE TITLE
SEMRush site audit of `demo.kedro.org`

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-website#90]
I ran a SEMRush audit across kedro.org this morning and it returned a couple of potential issues with `demo.kedro.org` which we could fix at some point (but I doubt are urgent in terms of SEO).

<img width="1124" alt="Screenshot 2023-03-07 at 11 28 26" src="https://user-images.githubusercontent.com/5180475/223410673-a4f2c473-c024-430d-80eb-982452431564.png">

I think the main ones are to add an H1, a meta description, and a title if possible. I wouldn't worry about most of the rest (text to HTML ratio or internal links). What about HSTS and compression? Is there anything we can do there?

**Comment by tynandebold** [comment]
![Screenshot 2023-03-07 at 13 11 50](https://user-images.githubusercontent.com/16869061/223432266-1981a808-99ad-4c5e-a67d-e9d8e3379781.png)

We have a `h1` tag. 

And we have a `title`, too. See that here: `view-source:https://demo.kedro.org/`.

Why isn't this tool picking those up? It makes the doubt the veracity of it.

I'm not inclined to think much about the rest. This is a demo page and the SEO seems quite good already. It's the first hit when searching for both **kedro demo** and **kedro viz demo**.

![image](https://user-images.githubusercontent.com/16869061/223433054-ccef6719-9ef4-4bf8-b919-ed0846cdd0a6.png)

**Comment by stichbury** [comment]
Interesting, thanks for looking at this @tynandebold  

* I think the issue with the `<title>` is that it is too short (9 characters) as per the report in the fifth row. 

* From an SEO perspective, I wouldn't doubt that we'd be the first hit for "Kedro demo" etc, but what we aren't reaching is organic search for keywords such as "Data science visualisation tool" or "Visualisation for data science pipelines". 

    * Shall I open a separate ticket to add a `meta` tag with some content for the tag? 
    * And *could* we consider a slightly longer title such as "Kedro-Viz pipeline visualisation demo" ? (Or would this need to be applied to the Viz product rather than the demo)?

**Comment by tynandebold** [comment]
The problem here is there's no differentiation between what's on the demo and what a user get's when they use Viz under normal circumstances. So if we added in your suggested title, that's fine for the demo, and probably not fine for a user who's running Viz locally.

We can beef up the meta tags without issue. If you want to create at ticket for that, that's no problem. It should live in the Viz repo though, not here.
