### ISSUE TITLE
Create designs and contentful template for a basic set of topic pages

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-website#93]
We've discussed previously. I'd like to add a set of pages to the website that contain content that isn't a blog post but isn't documentation. I always use the Ably topics pages https://ably.com/topics as my example. 

* We don't need to add these to the navigation
* We need a landing page template for "Kedro topics" or whatever we call it, with a set of thumbnail sections https://ably.com/topics
* We then need a topic page template to dump in article content rather like this one https://ably.com/topic/websockets-kafka (I'd see it styled much like a blog post but maybe without the author byline, certainly the requirements are similar).

I'm assuming this is a contentful template just to make it easier for you to hand off the regular work of creating the pages to me/content creators rather than having to keep creating separate web pages for new articles as they come along. But happy to discuss alternatives.

**Comment by tynandebold** [comment]
Relates to [#152](https://github.com/kedro-org/kedro-website/issues/152). Maybe these two pages should be handled in parallel?

**Comment by astrojuanlu** [comment]
Not doing this for now.
