### ISSUE TITLE
Contentful accounts for DevRel team

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-website#94]
Please could I request admin login access to Contentful for @stichbury and @astrojuanlu please? I don't think we have accounts yet?

There will be additional bloggers joining, so that's why I'm suggesting that we take on admin roles to create those accounts and save you from doing it @tynandebold. But if you prefer, just add us as editors and I'll let you know on a regular basis who we need to add from the team. External contributors may need a separate role/process but we've yet to get to that point.

Thank you!

**Comment by tynandebold** [comment]
You both need to create Contentful accounts and then I can add you to the organization. Let me know what email addresses you use for registration.

Please note that since we're on the "community tier" we can have a maximum of **five users** added to our org.

**Comment by stichbury** [comment]
Ah, perfect, will do that. I think we will need a generic "Kedro team" account and a "Kedroid" account for internal/external contributors and do a byline within the blog post to identify the authors. Let me think about how this works...

* Can we rotate Contentful users in and out of the site? So we have a blog post from User A via their Contentful account, then User B writes one and we publish theirs by kicking User A from the org and adding User B. Is this possible and, if so, what happens to the byline for User A?

**Comment by tynandebold** [comment]
- Can we rotate Contentful users in and out of the site? Yes.
- Is this possible and, if so, what happens to the byline for User A? Authors and bylines aren't tied to registered Contentful users. Instead, they're a content type we have full control over. So if User A writes a post, they'll select User A from the list of authors, and that will be the byline.

**Comment by stichbury** [comment]
I suppose I'm thinking of a process that looks like this:

1. External Kedroid writes a blog post and creates a Contentful account, which I add to the org
2. I upload their text as a post, select them from the list of authors and publish the post
3. The following week I kick them out of the org so I can add another Contentful account to the org because we hit the limit. 

Q: What happens to their post? Does the post remain published (I would hope so)? And is it still marked by that person, or is it now by an author known as `user deactivated` as per the Confluence model? That is, the org cannot any longer look up the details of contentful users that aren't part of it, so returns a "Not found" username.
 
I checked the docs myself and couldn't find an obvious answer. Except to say that I've left the Ably org but I'm still associated with posts (e.g. [this one](https://ably.com/topic/the-challenge-of-scaling-websockets)) without any problem...but I'm wondering if that's the case with a free edition. Anyway, we can try it out. 

If we can't shunt people in and out of the org, I quite like the idea of two anonymous users "Kedro maintainer" and "Kedroid" or something, and identifying the author properly in a callout box in the copy. So it's fine either way.

**Comment by tynandebold** [comment]
Why are they creating a Contentful account if you're the one publishing their post? In this instance, the post would remain there because you published it, not them.

Your point number two isn't dependent on point number one; a person can be an author **without** a having a Contentful account.

> If we can't shunt people in and out of the org, I quite like the idea of two anonymous users "Kedro maintainer" and "Kedroid" or something, and identifying the author properly in a callout box in the copy. So it's fine either way.

Regardless, I think we should start with this setup. It's less work for us.

**Comment by stichbury** [comment]
Closing this -- we both have accounts. Thanks!
